baseURL = ""
title = "Mallet James"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Mallet James"
    portrait = "ProfilePicZoomed3.png"
    description = "PSU Data Science '21"
    bio = """
    <p> My name is Mallet James and I am a junior studying Applied Data Science at Penn State University. My greatest interest in the field of Data Science is sports analytics and the application of statistics to sports. I currently serve as the president and founder of the <a href="https://sites.psu.edu/ssaclub/"><font color="blue">Penn State Sports Analytics Club</font></a> and contribute to <a href="https://stathouseanalytics.com/stats/team_rankings/2020_1_Men/"><font color="blue">StatHouse Analytics</font></a>, helping with development and various data science tasks in the context of college basketball. I also work alongside Penn State Track & Field providing help with data analysis.</p>
    <br />
    <p>My main interests in the area of sports analytics include basketball, baseball, and golf. I also enjoy predictive analytics and statistical modeling.</p>
    <br />
    <p> Contact: malletjames99@gmail.com </p>
    """
    copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."

    

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "/"
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://github.com/malletjames99"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/MalletJames3"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/mallet-james-84336a156/"
    name = "linkedin"
    weight = 2




